# Generated by Django 3.1 on 2020-09-27 06:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200927_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(error_messages={'blank': 'Поле надо заполнить!', 'unique': 'Поле должно быть уникальным!'}, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, db_index=True, default=blog.models.get_default_text, verbose_name='text'),
        ),
    ]
