# Generated by Django 3.1 on 2020-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200927_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='myid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='myid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(error_messages={'blank': 'Поле надо заполнить!', 'unique': 'Поле должно быть уникальным!'}, help_text='<i>Введите УРЛ для записи</i>', unique=True, verbose_name='url'),
        ),
    ]
